services:
  sinusbot:
    image: sinusbot-docker-custom:latest
    container_name: sinusbot-discord
    restart: always
    ports:
      - 38087:8087
    volumes:
      - ./scripts:/opt/sinusbot/scripts
      - ./data:/opt/sinusbot/data
      - ./tmp:/tmp
